# Generated by Django 3.0.4 on 2020-05-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_plan_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
    ]
